.PHONY: debug docs package single

# ========================== RECIPES FOR DEVELOPERS ========================== #

SANFLAGS ?= -fsanitize=address,undefined -fsanitize-trap

DISTDIR  := $(BINDIR)/dist
PACKAGES := $(DISTDIR)/nitroarc-embedded.tar.gz
PACKAGES += $(DISTDIR)/nitroarc-packaged.tar.gz
PACKAGES += $(DISTDIR)/nitroarc-vendored.tar.gz

debug: CFLAGS  += -O0 -g3 -Wno-unused-parameter -Wno-unused-function
debug: CFLAGS  += $(SANFLAGS)
debug: LDFLAGS += $(SANFLAGS)
debug: lib tool

docs:    $(patsubst doc/%.adoc,$(MANDIR)/%,$(wildcard doc/*.adoc))
single:  $(BINDIR)/nitroarc.c
package: $(PACKAGES)

# =========================== TARGET CONFIGURATION =========================== #

$(BINDIR)/nitroarc.c: lib/nitroarc_private.h $(SRC_C) | $(BINDIR)
	head -n 18 $< > $@
	echo '#include "nitroarc.h"' >> $@
	echo >> $@

	tail -n +19 $< >> $@
	tail -qn +20 $(LIB_C)  \
		| grep -v '#endif' \
		| grep -v 'private\.h' \
		>> $@

$(MANDIR)/%: doc/%.adoc
	asciidoctor -b manpage -o $@ $<

# For library embedding; provide the amalgamated library source
$(DISTDIR)/nitroarc-embedded.tar.gz: single | $(BINDIR)
	$(RM) -r $(@D)/nitroarc && mkdir -p $(@D)/nitroarc
	ln -sf $$PWD/COPYING $(@D)/nitroarc/COPYING
	ln -sf $$PWD/COPYING.LESSER $(@D)/nitroarc/COPYING.LESSER
	ln -sf $$PWD/lib/include/nitroarc.h $(@D)/nitroarc/nitroarc.h
	ln -sf $$PWD/bin/nitroarc.c $(@D)/nitroarc/nitroarc.c
	tar czf $@ -C $(@D) --dereference nitroarc

# For toolchain installation; provide the base Makefile and compiled manuals
$(DISTDIR)/nitroarc-packaged.tar.gz: docs | $(BINDIR)
	$(RM) -r $(@D)/nitroarc && mkdir -p $(@D)/nitroarc $(@D)/nitroarc/man
	ln -sf $$PWD/COPYING $(@D)/nitroarc/COPYING
	ln -sf $$PWD/COPYING.LESSER $(@D)/nitroarc/COPYING.LESSER
	ln -sf $$PWD/ffi $(@D)/nitroarc/ffi
	ln -sf $$PWD/$(MANDIR)/nitroarc.1 $(@D)/nitroarc/man/nitroarc.1
	ln -sf $$PWD/$(MANDIR)/nitroarc.3 $(@D)/nitroarc/man/nitroarc.3
	ln -sf $$PWD/lib $(@D)/nitroarc/lib
	ln -sf $$PWD/src $(@D)/nitroarc/src
	grep -v "^include Makefile\..*" Makefile \
		| sed -E "s|MANDIR   := $(BINDIR)/man|MANDIR   := man|" \
		> $(@D)/nitroarc/Makefile
	tar czf $@ -C $(@D) --dereference nitroarc

# For vendoring in a project tree; provide the plain-text documentation files
$(DISTDIR)/nitroarc-vendored.tar.gz: docs single | $(BINDIR)
	$(RM) -r $(@D)/nitroarc && mkdir -p $(@D)/nitroarc $(@D)/nitroarc/lib
	ln -sf $$PWD/COPYING $(@D)/nitroarc/COPYING
	ln -sf $$PWD/COPYING.LESSER $(@D)/nitroarc/COPYING.LESSER
	ln -sf $$PWD/doc $(@D)/nitroarc/doc
	ln -sf $$PWD/ffi $(@D)/nitroarc/ffi
	ln -sf $$PWD/lib/include $(@D)/nitroarc/lib/include
	ln -sf $$PWD/bin/nitroarc.c $(@D)/nitroarc/lib/nitroarc.c
	ln -sf $$PWD/src $(@D)/nitroarc/src
	tar czf $@ -C $(@D) --dereference nitroarc
